# app_config.yaml  (place beside app_spf_Portal.py in the repo root)

credentials:
  usernames:
    brad:
      name: Brad
      email: brad@example.com
      password: "$2b$12$.n87oFQoP03GYkzoQUFGr.Ni0csX626Q7FhUuEmVNH4GniOwW9TBe"
    demo:
      name: Demo User
      email: demo@example.com
      password: "$2b$12$d9r3v4j3K2o2uI6dFoyVbOa3YV1Aq8p2qTj6kQy0iv8y2dQk6gV2W"

cookie:
  name: spf_po_portal
  key: change_me_in_yaml
  expiry_days: 7

access:
  admin_usernames: [brad]
  user_companies:
    brad: ['*']
    demo: ['*']

settings:
  # <<< point explicitly to the DB that lives in this repo >>>
  db_path: "./maintainx_po.db"

  # (optional) If you aren’t using Parquet, remove this block entirely.
  # parquet:
  #   restock: ""
  #   po_outstanding: ""

