credentials:
  usernames:
    brad:
      name: Brad
      email: brad@example.com
      password: "$2b$12$.n87oFQoP03GYkzoQUFGr.Ni0csX626Q7FhUuEmVNH4GniOwW9TBe"
    demo:
      name: Demo User
      email: demo@example.com
      password: "$2b$12$d9r3v4j3K2o2uI6dFoyVbOa3YV1Aq8p2qTj6kQy0iv8y2dQk6gV2W"

cookie:
  name: spf_po_portal
  key: "use-a-long-random-string-here"
  expiry_days: 7

access:
  admin_usernames: [brad]
  user_companies:
    brad: ['*']
    demo: ['*']

settings:
  db_path: "./maintainx_po.db"   # <— DB lives next to the app file

  # (remove or leave commented if you’re not using Parquet)
  # parquet:
  #   restock: ""
  #   po_outstanding: ""
